const dataset_example = [
  {
    index: 1,
    city: "Zurich",
    occupation: "Operations Manager",
    field: "Operations",
    years: 16,
    salary: 359609,
    type: "work_from_home",
    education: "Master",
    gender: "Male",
    size: "Large",
    year: 2023,
    month: 8,
  },
  {
    index: 2,
    city: "Paris",
    occupation: "Data Scientist",
    field: "IT",
    years: 5,
    salary: 95000,
    type: "onsite",
    education: "Master",
    gender: "Female",
    size: "Medium",
    year: 2022,
    month: 6,
  },
  {
    index: 3,
    city: "Berlin",
    occupation: "Software Engineer",
    field: "IT",
    years: 3,
    salary: 72000,
    type: "remote",
    education: "Bachelor",
    gender: "Male",
    size: "Startup",
    year: 2023,
    month: 3,
  },
  {
    index: 4,
    city: "Madrid",
    occupation: "HR Manager",
    field: "HR",
    years: 10,
    salary: 60000,
    type: "onsite",
    education: "Master",
    gender: "Female",
    size: "Large",
    year: 2021,
    month: 11,
  },
  {
    index: 5,
    city: "London",
    occupation: "Product Manager",
    field: "Product",
    years: 8,
    salary: 110000,
    type: "hybrid",
    education: "Master",
    gender: "Male",
    size: "Large",
    year: 2023,
    month: 1,
  },
  {
    index: 6,
    city: "New York",
    occupation: "Financial Analyst",
    field: "Finance",
    years: 6,
    salary: 98000,
    type: "onsite",
    education: "Bachelor",
    gender: "Male",
    size: "Medium",
    year: 2022,
    month: 9,
  },
  {
    index: 7,
    city: "Tokyo",
    occupation: "UX Designer",
    field: "Design",
    years: 4,
    salary: 65000,
    type: "remote",
    education: "Bachelor",
    gender: "Female",
    size: "Startup",
    year: 2023,
    month: 4,
  },
  {
    index: 8,
    city: "Dubai",
    occupation: "Sales Manager",
    field: "Sales",
    years: 12,
    salary: 120000,
    type: "onsite",
    education: "Bachelor",
    gender: "Male",
    size: "Large",
    year: 2022,
    month: 7,
  },
  {
    index: 9,
    city: "Toronto",
    occupation: "DevOps Engineer",
    field: "IT",
    years: 7,
    salary: 105000,
    type: "hybrid",
    education: "Master",
    gender: "Female",
    size: "Medium",
    year: 2023,
    month: 2,
  },
  {
    index: 10,
    city: "Amsterdam",
    occupation: "Marketing Specialist",
    field: "Marketing",
    years: 5,
    salary: 58000,
    type: "remote",
    education: "Bachelor",
    gender: "Female",
    size: "Startup",
    year: 2021,
    month: 10,
  },
  {
    index: 499999,
    city: "...",
    occupation: "...",
    field: "...",
    years: 0,
    salary: 0,
    type: "...",
    education: "...",
    gender: "...",
    size: "...",
    year: 0,
    month: 0,
  },
];

const occupation = [
  "Operations Manager",
  "HR Analyst",
  "Software Engineer",
  "Cloud Engineer",
  "UX Designer",
  "Marketing Specialist",
  "Business Analyst",
  "Financial Analyst",
  "Data Scientist",
  "Data Analyst",
  "Product Manager",
  "AI Engineer",
];

const city = [
  "Zurich",
  "Bangalore",
  "Stockholm",
  "Seoul",
  "New York",
  "Mexico City",
  "Sydney",
  "Dubai",
  "Paris",
  "San Francisco",
  "Sao Paulo",
  "Toronto",
  "Madrid",
  "Milan",
  "Auckland",
  "Amsterdam",
  "Singapore",
  "Dublin",
  "Cape Town",
  "Tokyo",
  "London",
  "Berlin",
];

const field = [
  "Operations",
  "Human Resources",
  "Technology",
  "Design",
  "Marketing",
  "Business",
  "Finance",
];

const employment_type = [
  "work_from_home",
  "part_time",
  "freelance",
  "full_time",
  "internship",
];

const education_level = ["Master", "PhD", "Bachelor", "High School"];

const gender = ["Male", "Female", "Other"];

const company_size = ["Large", "Enterprise", "Medium", "Small"];

export { dataset_example, occupation, city, gender, education_level, company_size, employment_type, field };